### ISSUE TITLE
AdjustConfig.deactivateSKAdNetworkHandling missing from type definition

### ISSUE THREAD

**Issue by smacgregor** [adjust/react_native_sdk#102]
I think index.d.ts is missing a type declaration for AdjustConfig deactivateSKAdNetworkHandling.

**Comment by uerceg** [comment]
Hey @smacgregor 

Yes it is, we're on it to have it merged to ionic-native repo. Will keep you posted.

**Comment by uerceg** [comment]
Hey @smacgregor,

Thanks for your patience. We just released [v4.26.0](https://github.com/adjust/react_native_sdk/releases/tag/v4.26.0) update which should address this issue as well.

In case you have any further questions, feel free to comment/reopen.

Cheers
