### ISSUE TITLE
requestTrackingAuthorizationWithCompletionHandler not working 

### ISSUE THREAD

**Issue by SamyOptimize** [adjust/react_native_sdk#112]
Based on #111 I have added the missing type definition but I'm still unable to get the function to work.

I have added the same code from the example code like so and set up my adjustConfig object 
```
Adjust.requestTrackingAuthorizationWithCompletionHandler((status) => {
      console.log("Authorization status update", status);
      switch (status) {
        case 0:
          // ATTrackingManagerAuthorizationStatusNotDetermined case
          console.log(
            "Authorization status: ATTrackingManagerAuthorizationStatusNotDetermined"
          );
          break;
        case 1:
          // ATTrackingManagerAuthorizationStatusRestricted case
          console.log(
            "Authorization status: ATTrackingManagerAuthorizationStatusRestricted"
          );
          break;
        case 2:
          // ATTrackingManagerAuthorizationStatusDenied case
          console.log(
            "Authorization status: ATTrackingManagerAuthorizationStatusDenied"
          );
          break;
        case 3:
          // ATTrackingManagerAuthorizationStatusAuthorized case
          console.log(
            "Authorization status: ATTrackingManagerAuthorizationStatusAuthorized"
          );
          break;
      }
    });
```
But nothing gets logged

**Comment by uerceg** [comment]
Hi @SamyOptimize 

Unrelated to your issue, just for the record - that PR is to be part of our next release, hopefully we're gonna start working on it soon.

Regarding your issue:
- Do you have `AppTrackingTransparency.framework` linked to your iOS app?
- Do you have `NSUserTrackingUsageDescription` key set in iOS app's `Info.plist` file with text which should be displayed in pop up dialog?

**Comment by SamyOptimize** [comment]
Hi @uerceg thanks for the prompt reply. 

I wasn't aware i needed to link the `AppTrackingTransparency.framework`, after doing so i'm able to get the ATT prompt to appear. 

Thank you

**Comment by uerceg** [comment]
Amazing. 👍 In case you have any further question or if there's need to - feel free to reopen/comment. Cheers.

**Comment by andrewdazs** [comment]
I'm having this problem too. But I'm testing it on a simulator (iPhone 8, iOS 14). Can this work on a simulator or only on a real device?

**Comment by RKhatri93** [comment]
I am facing the same problem. 
Do you have AppTrackingTransparency.framework linked to your iOS app? -> Yes
Do you have NSUserTrackingUsageDescription key set in iOS app's Info.plist file with text which should be displayed in pop up dialog? -> Yes

I am testing it on iPhone 14 simulator
