### ISSUE TITLE
Version 4.25

### ISSUE THREAD

**Issue by cipriancaba** [adjust/react_native_sdk#113]
Is there any way to use the new apple attribution api on react native? https://www.adjust.com/product-updates/adjusts-latest-ios-sdk-supports-new-apple-ads-attribution-api/

**Comment by uerceg** [comment]
Hey @cipriancaba 

Yes, it's gonna be part of our next React Native SDK update we're working on. Will keep you posted when it's live.

**Comment by rborn** [comment]
@uerceg any eta? 🥰

**Comment by uerceg** [comment]
Hey @rborn 

Yes, next aiming for next week. Will keep you posted!

**Comment by rborn** [comment]
@uerceg lovely, thank you 😻

**Comment by Tripwire999** [comment]
Any news on the update?

**Comment by uerceg** [comment]
Yep. Tomorrow most probably.

**Comment by uerceg** [comment]
Hey guys,

Thanks for your patience. We just released [v4.26.0](https://github.com/adjust/react_native_sdk/releases/tag/v4.26.0) update which should be aligned with all the features which native SDKs currently offer.

In case you have any further questions, feel free to comment/reopen.

Cheers
