### ISSUE TITLE
Unable to read url / params added in Deferred Deeplink

### ISSUE THREAD

**Issue by codemeall** [adjust/react_native_sdk#118]
Example link  `https://ab12.adj.st/adjust_t=ab12?deep_link=myappscheme://my/params`

The link only opens my app but ain't able to read deep link params

**Comment by uerceg** [comment]
Hi @codemeall 

And sorry for delayed reply on this one. Are you still unable to read parameters from deep link? Where are you getting the link inside of your app and how does it look like? Also I think that you should URL encode value of the `deep_link` parameter. So tracker URL should look something like this: https://ab12.adj.st/adjust_t=ab12?deep_link=myappscheme%3A%2F%2Fmy%2Fparams.

Cheers

**Comment by uerceg** [comment]
Hi @codemeall 

Any update on this one? Did you manage to make things work or are you still facing this issue?

Cheers

**Comment by uerceg** [comment]
If you're still facing this issue, feel free to comment / reopen. Cheers.
