### ISSUE TITLE
Adjust Install, Track Event triggers multiple times in same timestamp after 4.28.0 sdk installation in app

### ISSUE THREAD

**Issue by Hemistone** [adjust/react_native_sdk#120]
Before using 4.28.0 sdk, we used 4.26.0 sdk in our rn apps and almost every events called single times correctly.

However after installing 4.28.0 sdk, many of install event and track events randomly called 2~3 times in same timestamp.
This phenomenon is more frequently happened in first session(first app open after installing app), but also happens in apps with higher number sessions.

I don't know if this is a critical dependency in your event trigger logic, but as in case we are using codepush for our OTA updates.

We are getting track events and install events from adjust's realtime callback which is configured in adjust web console.

Can you please check out is there any problem with newest rn sdk or server related with this issue?

**Comment by uerceg** [comment]
Hi @Hemistone,

It definitely should not be the case (tracking same event(s) multiple times). Is this something you can reproduce while testing your debug build?

**Comment by Hemistone** [comment]
Okay I will first test events in debug build with sandbox environments Thank you.

**Comment by Hemistone** [comment]
Sorry @uerceg , after testing several times we found that it was our data science team's fault. I will close this issue.
