### ISSUE TITLE
Dependency on create-react-native-app due to example app update

### ISSUE THREAD

**Issue by kelleyvanevert** [adjust/react_native_sdk#121]
I updated the SDK and noticed that that an unnececssary dependency on `create-react-native-app` crept into the library, as an accident probably of updating the example app. See the relevant commit:

https://github.com/adjust/react_native_sdk/commit/2eda2be6fd8836303e73d6474357e1d87b2a1ed0

Would be nice if this could be removed again :)

**Comment by TNicholson11** [comment]
Seconded. Very odd to see this included.

**Comment by uerceg** [comment]
Hey guys,

Sorry for delay in here as well. I just replied to @kelleyvanevert's [commit comment](https://github.com/adjust/react_native_sdk/commit/2eda2be6fd8836303e73d6474357e1d87b2a1ed0#commitcomment-53855152) and we're gonna address this in next patch release.

Odd indeed and should not be there at all. Will keep you posted.

**Comment by uerceg** [comment]
Hey guys. We just released [v4.29.2](https://github.com/adjust/react_native_sdk/releases/tag/v4.29.2) update to address this issue. Sorry one more time for waiting and thank you for reporting the issue. In case you have any other questions / comments, feel free to comment/reopen if needed. Cheers!
