### ISSUE TITLE
Subscription Tracking Issue

### ISSUE THREAD

**Issue by VickyStash** [adjust/react_native_sdk#122]
When I try to track Google Play subscription with Adjust.trackPlayStoreSubscription I see these logs in Android Studio, but I see no tracked subscription in the dashboard and I'm not sure why. 
(I've followed steps from https://help.adjust.com/en/article/subscription-tracking)

![image](https://user-images.githubusercontent.com/23176449/117044959-a7713780-ad17-11eb-8f54-82ef882289e1.png)

**Comment by uerceg** [comment]
Hi @VickyStash 

Does your account have subscription tracking package activated?

**Comment by uerceg** [comment]
In case this is still an issue, feel free to ping your dedicated account manager or if you don't have one, fire an email to support@adjust.com because our support team will definitely be able to help you troubleshoot things quickly on this topic. Cheers.
