### ISSUE TITLE
Unable to see verbose logs

### ISSUE THREAD

**Issue by mbr93** [adjust/react_native_sdk#129]
Hi,

I'm trying to enable verbose logging in our app but I'm unable to see anything in the terminal.

Steps to reproduce:
1. setLogLevel to AdjustConfig.LogLevelVerbose
2. start the app
3. click some buttons with adjust events attached to them

Expected:
Some adjust logs are visible in the console

Actual:
Nothing coming from Adjust is being displayed

Here is the code:

App.tsx
```
import { Adjust, AdjustConfig } from "react-native-adjust";

(...)

const setupAdjust = async () => {
    const adjustConfig = new AdjustConfig(AdjustConfig.EnvironmentSandbox);
    adjustConfig.setLogLevel(AdjustConfig.LogLevelVerbose);
    Adjust.create(adjustConfig);
    Adjust.setEnabled(true);
  };

useEffect(() => {
          setupAdjust();
  }, []);
```

We trigger the events in the following way:
```
const adjustEvent = new AdjustEvent(eventName);
    Adjust.trackEvent(adjustEvent);
```

This happens on both platforms (Android and iOS).
The version we're using is 4.28.0

Would somebody be able to help?

**Comment by uerceg** [comment]
Hi @mbr93 

Where are you looking for the logs? Adjust SDK doesn't print logs from Javascript layer, they are all native logs. So in theory, you either run your apps from native Xcode and/or Android Studio projects and check for the SDK logs in there, or if you're not using Xcode / Android Studio, then you can check macOS Console app for iOS native logs or **adb logcat -s Adjust** to get native Android logs.
