### ISSUE TITLE
Publish 4.29.3 to npm

### ISSUE THREAD

**Issue by smacgregor** [adjust/react_native_sdk#131]
Is it possible to publish a new version of react_native_sdk to pick up [IOS 4.29.3](https://github.com/adjust/ios_sdk/releases/tag/v4.29.3)?  This will allow the package to build on xCode 13. 

Thanks!

**Comment by uerceg** [comment]
Hi @smacgregor 

Yep, will be live this week. Will keep you posted.

Cheers!

**Comment by uerceg** [comment]
Hi @smacgregor

We have released React Native SDK v4.29.0 which contains native iOS SDK 4.29.3 under the hood. Feel free to give it a shot and let us know if it worked with Xcode 13 for you.

Cheers

**Comment by smacgregor** [comment]
It worked great! Thank you.
