### ISSUE TITLE
Deep link dynamic parameters cropped

### ISSUE THREAD

**Issue by raienko** [adjust/react_native_sdk#133]
Hi, @uerceg .
Could you help me, please:

Is there any way to path and parse custom dynamic parameters to deferred/deep links?

What do we want:
UserA should send deferred_link + param `username=UserA` to User B.
UserB should be able to get `username` param from link after app installation

Example:
link
`https://app.adjust.com/f0ob4r?deep_link=myapp://test_page&username=test`
opens app, but url is:
`myapp://test_page?adjust_reftag=f0ob4r`
all custom params cropped

Is there any way to receive:
`myapp://test_page?adjust_reftag=f0ob4r&username=test` ?

**Comment by uerceg** [comment]
Hi @raienko 

Sorry for delay in here. Hm. Interesting. Just to double check trivial things at the start - are you URL encoding the value of `deep_link` parameter from that URL and using it like https://app.adjust.com/f0ob4r?deep_link=myapp%3A%2F%2Ftest_page%26username%3Dtest ?

**Comment by uerceg** [comment]
In case you're still facing this issue, feel free to comment / reopen. Cheers.
