### ISSUE TITLE
Crashed in iOS - wrong sdkVersionChar variable in ADJPackageBuilder.m

### ISSUE THREAD

**Issue by ridvanaltun** [adjust/react_native_sdk#140]
Hey,

I compiled the iOS application successfully, but the application crashes when opening. I don't know the Objective C language, but as far as I can tell, a variable named sdkVersionChar in the ADJPackageBuilder.m file is set incorrectly, so the strncpy function throws an error. You can see what I mean by looking at the xcode debug screenshot below.

**react-native-adjust version:** 4.29.3

<img width="1428" alt="Screen Shot 2021-08-17 at 16 36 05" src="https://user-images.githubusercontent.com/10441216/129735966-251f0ed2-ac23-48c7-9b16-49d9aba72036.png">

By the way I resolved this issue changing sdkVersion variable definition like below in 310's line but i don't know can it break something else:

```c
// old
sdkVersion[21];

// new
sdkVersion[50];
```

**Comment by uerceg** [comment]
Hi @ridvanaltun 

Thanks for reporting this and for the detailed explanation. We'll try to address this as soon as we can (natively + update React Native SDK as well). Will keep you posted.

**Comment by uerceg** [comment]
Hi @ridvanaltun 

We have just released [v4.29.4](https://github.com/adjust/react_native_sdk/releases/tag/v4.29.4) update which should hopefully address this issue. Feel free to give it a shot and let us know if it fixed the issue you were facing with or is it still present.

Looking forward to hearing back from you.

**Comment by ridvanaltun** [comment]
> Hi @ridvanaltun
> 
> We have just released [v4.29.4](https://github.com/adjust/react_native_sdk/releases/tag/v4.29.4) update which should hopefully address this issue. Feel free to give it a shot and let us know if it fixed the issue you were facing with or is it still present.
> 
> Looking forward to hearing back from you.

Works like a charm!
