### ISSUE TITLE
Cannot pod install new version

### ISSUE THREAD

**Issue by hassey13** [adjust/react_native_sdk#146]
Trying to update to latest version to fix error for 

```
Adjust

/Users/eric/nvstr/repos/nvstr-mobile-react-native/ios/Pods/Adjust/Adjust/Adjust.m:274:16: Multiple methods named 'attribution' found with mismatched result, parameter type or attributes
```

```
package.json

"react-native-adjust": "^4.29.4",
```

```
[!] CocoaPods could not find compatible versions for pod "Adjust":
  In Podfile:
    react-native-adjust (from `../node_modules/react-native-adjust`) was resolved to 4.29.4, which depends on
      Adjust (= 4.29.5)

None of your spec sources contain a spec satisfying the dependency: `Adjust (= 4.29.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by hassey13** [comment]
I was able to fix this issue by clearing the pod cache and then manually targeting an update of the pod, I believe something is misconfigured in the auto-linking modules

**Comment by akimabs** [comment]
any update ?

**Comment by voxspox** [comment]
same issue here. I did:
- updated react-native-adjust in the package.json to 0.29.4
- run `npm install`
- run `pod install`

```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Adjust":
  In snapshot (Podfile.lock):
    Adjust (= 4.28.0)

  In Podfile:
    react-native-adjust (from `../node_modules/react-native-adjust`) was resolved to 4.29.4, which depends on
      Adjust (= 4.29.5)
```

Last version is 0.29.**4** so I'm wondering how the *.5 comes into play

**Comment by voxspox** [comment]
tried suggested workaround from above:
```
$ pod update Adjust
Analyzing dependencies
Downloading dependencies
Installing Adjust 4.29.5 (was 4.28.0)
Installing react-native-adjust 4.29.4 (was 4.28.0)
Generating Pods project
Integrating client project
...
$
```

**Comment by uerceg** [comment]
Hey guys,

Sorry for delay on this one. Version of the pod named `Adjust` is independent from version of the React Native SDK which is hosted in npm repo. So underlying version of native Adjust SDK (which is being pulled from Cooapods) can be different from React Native plugin version.

Did updating pod worked for you?

**Comment by cihangir-mercan** [comment]
If there is no solution, it may mean that you are working in a closed environment. And your company's inner jfrog pods may not contain that version.
