### ISSUE TITLE
React native 0.66 upgrade causes NativeEventEmitter warning

### ISSUE THREAD

**Issue by muhabutt** [adjust/react_native_sdk#147]
I have upgraded react-native version from 0.64 to 0.66. When running the app on Android, i get this warning.

**new NativeEventEmitter() was called with a non-null argument without the required addListener method.**

**Comment by ken0nek** [comment]
This fix might be related and helpful?
https://github.com/dooboolab/react-native-iap/pull/1524/files

**Comment by muhabutt** [comment]
> This fix might be related and helpful? [dooboolab/react-native-iap#1524](https://github.com/dooboolab/react-native-iap/pull/1524)

But this should be done by Adjust.

**Comment by uerceg** [comment]
Fix for this should be part of the just released [v4.29.5](https://github.com/adjust/react_native_sdk/releases/tag/v4.29.5) update. Thank you for your patience and @ken0nek, thank you for the PR!

In case issue still persists, feel free to comment/reopen.

Cheers.
