### ISSUE TITLE
iPad iOS 14.4 returns Not Determined instead of Restricted when App Tracking is disabled

### ISSUE THREAD

**Issue by SirBenWard** [adjust/react_native_sdk#148]
I have an iPad Air/Mini 4 with App Tracking disabled, yet returning `Not Determined` instead of `Restricted` when calling `getAppTrackingAuthorizationStatus`. I am also calling this function twice at separate times. This also causes calls to `requestTrackingAuthorizationWithCompletionHandler` to not return any result.

Oddly enough, I haven't seen this issue on iPhone devices.

**Comment by uerceg** [comment]
Hey guys,

Sorry for delay on this one. Hm. Interesting. May I ask how do you know that restricted state is the one which you're expecting to get back?

**Comment by uerceg** [comment]
If help is still needed, feel free to comment / reopen. Cheers.
