### ISSUE TITLE
DataResidencyEU is missing on AdjustConfig type

### ISSUE THREAD

**Issue by pke** [adjust/react_native_sdk#157]
`Property 'DataResidencyEU' does not exist on type 'typeof AdjustConfig'.`

**Comment by uerceg** [comment]
Hi @pke,

Are you using Typescript definitions? If yes, are you using latest Adjust React Native SDK version and latest Typescript definitions from https://github.com/danielsogl/awesome-cordova-plugins?

**Comment by pke** [comment]
Latest SDK. It contains typing I thought. So you are saying I need to install the cordova plugin even when using react native?

**Comment by uerceg** [comment]
Oh my. Sorry for that. I confused repos. 🤦‍♀️ You shouldn't, of course. We'll double check and let you know.

**Comment by uerceg** [comment]
Yep, not all `AdjustConfig` constants from `index.js` were added to TypeScript API in `index.d.ts`. Will be fixed in next patch release. Will keep you posted and take a look at [this one](https://github.com/adjust/react_native_sdk/issues/158) as well.

**Comment by uerceg** [comment]
@pke Can you give latest plugin version (4.29.6) a shot and let us know if you're still facing this issue? Thank you in advance.

**Comment by pke** [comment]
Its fixed in 4.29.6
Thanks!
