### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'create'), ANDROID

### ISSUE THREAD

**Issue by sheydarezaee** [adjust/react_native_sdk#162]
I am implementing the sdk on react native project with react native version `0.64.2`, and NOT using expo.
This is the initialization of the sdk, but can not read create method:

`import { Adjust, AdjustConfig } from 'react-native-adjust'`
`constructor(props) {`
    `super(props);`
    `const adjustConfig = new AdjustConfig("{YourAppToken}", AdjustConfig.EnvironmentSandbox);`
    `Adjust.create(adjustConfig);`
}`

`componentWillUnmount() {
  Adjust.componentWillUnmount();
}`

This is the error shown:
<img width="567" alt="Screen Shot 2022-02-16 at 5 04 53 PM" src="https://user-images.githubusercontent.com/19738414/154559675-803e1e38-236a-4f0a-a076-65eac6366057.png">

or if I try to get sdk version by:
 `Adjust.getSdkVersion(function(sdkVersion) {
    console.log("Adjust SDK version: " + sdkVersion)
 })`

<img width="588" alt="Screen Shot 2022-02-17 at 10 57 50 AM" src="https://user-images.githubusercontent.com/19738414/154559696-3fc07223-5408-407c-9b3b-d3b4cb0b9165.png">

I tried running the sample project, and still getting the same issue. Any hints would be appreciated.

    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-adjust": "^4.29.6",

**Comment by uerceg** [comment]
Hi @sheydarezaee,

Which platform are you running your app on (iOS / Android)?

**Comment by uerceg** [comment]
Hi @sheydarezaee,

Any update on this one?

**Comment by sheydarezaee** [comment]
@uerceg it is on android

**Comment by sheydarezaee** [comment]
![image](https://user-images.githubusercontent.com/19738414/155173476-7f3a2b9a-124e-42c0-a2de-1fb71b480143.png)

**Comment by sheydarezaee** [comment]
to manually link the android side, here is what I did:

- added to `settings.gradle`:
`include ':react-native-adjust'
project(':react-native-adjust').projectDir = new File("$rootDir/../node_modules/react-native-adjust/android")`

- added to `build.gradle`:
`implementation project(':react-native-adjust')`

but still get `module_adjust` as undefined ...
<img width="963" alt="Screen Shot 2022-02-22 at 8 30 15 AM" src="https://user-images.githubusercontent.com/19738414/155175849-130aa007-6e9f-43a2-ac1f-c9398799e56b.png">

**Comment by DaveMeadAdjust** [comment]
Hi @sheydarezaee,

Did you also include the package in your MainApplication.java file as described in [this post](https://medium.com/@bala.krishnan/react-native-auto-linking-on-android-65a850bb9ed9)?

**Comment by sheydarezaee** [comment]
Looking in to it @DaveMeadAdjust

**Comment by uerceg** [comment]
Thank you @sheydarezaee for an update. I'm going to close this ticket, but in case you still have any further questions, feel free to comment / reopen. Cheers!
