### ISSUE TITLE
React Native version compatibility

### ISSUE THREAD

**Issue by ca057** [adjust/react_native_sdk#169]
Hello adjust-team!

We’re using the SDK in our app but are facing issues when upgrading React Native. After upgrading React Native, we don’t see events from adjust ending up in the dashboard (or via the testing console).

I’ve tested it with both `react-native-adjust@4.29.5` and `react-native-adjust@4.29.6`. As soon as we upgrade from `react-native@0.66.4` to `react-native@0.67.3` the errors mentioned above occur.

What is the supported React Native version of the SDK?
Are these known issues with the SDK or is this something on our side?
Do you need any additional information from my side?

**Comment by Aditi3** [comment]
Hey @ca057, 

Apologies for the delayed response. We investigated the aforementioned scenario on our end but were unable to reproduce the behaviour.  

Could you share the verbose level debug log with us so that we can debug this further?

**Comment by uerceg** [comment]
Hi @ca057,

Are there maybe any updates on this one? In theory, our SDK should work fine with all of those `react-native` versions. Are you still facing this issue? If yes, are you also facing it with latest v4.31.0 release?

**Comment by uerceg** [comment]
In case the issue is still around (also make sure to give [latest version](https://github.com/adjust/react_native_sdk/releases/tag/v4.32.0) a shot), feel free to comment / reopen.

Cheers
