### ISSUE TITLE
Remove usages of `jcenter()`

### ISSUE THREAD

**Issue by jordanjoecooper** [adjust/react_native_sdk#176]
Please remove usages of `jcenter()` Maven repository from your build and migrate to other Maven repositories.

The jcenter repository is deprecated and it will be shut down in the future.

See googles [end of service doc](http://developer.android.com/r/tools/jcenter-end-of-service) for more information.

**Comment by uerceg** [comment]
Hi @jordanjoecooper,

And sorry for delay in replying. Thank you for the suggestion, absolutely makes sense. Just to make sure - are you referring to [jcenter() mention in this README chapter](https://github.com/adjust/react_native_sdk/#google-play-referrer-api) or somewhere else?

**Comment by uerceg** [comment]
With latest PR, we have removed mention of `jcenter` from README as well. In case you still see it being used somewhere where it shouldn't be, please let us know. Cheers.
