### ISSUE TITLE
Google Play Services section

### ISSUE THREAD

**Issue by dhpwd** [adjust/react_native_sdk#182]
Re the [Google Play Services](https://github.com/adjust/react_native_sdk#google-play-services) section, `com.google.android.gms:play-services-analytics` is now deprecated

See https://developers.google.com/android/guides/setup

<img width="710" alt="Screenshot 2022-06-02 at 16 03 34" src="https://user-images.githubusercontent.com/1770050/171660218-24dadbca-dc80-45de-9cac-47777d833583.png">

Should be e.g. `com.google.android.gms:play-services-ads-identifier:18.0.1` instead

**Comment by uerceg** [comment]
Hi @dhpwd,

Thank you for flagging this and sorry for delay on our end in getting back to you. Exactly what you suggested has now been added to our README.

In case you still have any questions, feel free to comment / reopen.
