### ISSUE TITLE
Using native libraries instead of raw {.h,.m} classes in ios module

### ISSUE THREAD

**Issue by namini40** [adjust/react_native_sdk#184]
hi 
lately I've been looking at adjust sdk for react native and I come across ios module. apparently this part we handled by all classes from ios sdk just copied into the module. I was wondering if it is for simplicity or it can be done using podspec file and just calling SDK's APIs or xcframeworks?
I wanted to do it but first I figured I might ask before...
thanks as always

**Comment by uerceg** [comment]
Hi @namini40,

Thanks for the question and sorry for delay in replying. Historically we started the React Native SDK with having native iOS SDK source files added to it and that's pretty much how things remained til today. In theory, I don't think that anything is effectively preventing us from swapping source files with some type of (xc)framework instead, but like said - simply, was never asked by anyone and we still didn't get to that topic internally. :)

In case you have any further questions, feel free to ask.

Cheers

**Comment by namini40** [comment]
thank you @uerceg I understood and it makes sense. 🍻
