### ISSUE TITLE
Autolinking does not work with React Native 0.69.0

### ISSUE THREAD

**Issue by Naturalclar** [adjust/react_native_sdk#185]
# Issue
Due to change in react-native cli, https://github.com/react-native-community/cli/pull/1537
Autolinking is no longer working with React Native 0.69

## Expected Behavior
React Native autolinking to work with react-native-adjust

## Repro Steps:
Create a new React Native Project version 0.69
install react-native-adjust
run pod install in ios directory
Notice that RNNotifications is not included in the Podfile.lock

Repro repository
[Naturalclar/react-native-notifications-repro](https://github.com/Naturalclar/react-native-notifications-repro)

**Comment by uerceg** [comment]
Hi @Naturalclar,

We have just added suggested changes to our [latest v4.31.0 release](https://github.com/adjust/react_native_sdk/releases/tag/v4.31.0).

If you can give it a shot and let us know if that fixed your issue, would be great.

**Comment by Naturalclar** [comment]
@uerceg 
seems to be working fine! thanks
