### ISSUE TITLE
Missing tracking in all but not 'development' builds

### ISSUE THREAD

**Issue by andrebiel** [adjust/react_native_sdk#187]
I'm running adjust in a `bare` expo (react-native) application. Expo version is 44 and adjust package version is 4.29.6. I'm building with EAS.

In general, I have two questions/issues, which I would highly appreciate your help: 

1. If I'm using the testing console to inspect my device, I will only see data if the build is a development build (e.g. run on my device with the `--start-client` flag). On every other (standalone) build my device data won't ever show up. Do you have know a reason why this would happen?

2. Im using session callback handlers as described in the documentation. But neither the success handler nor the error handler fires in standalone builds. Can I expect a session callback to be fired on **every** session? As a result: If no handler fires, something is wrong?

Thanks in advance

**Comment by uerceg** [comment]
Hey @andrebiel,

Sorry for a bit of delay.

1. I am not actually sure why is that you are not seeing traffic from these other builds on the testing console. We who are first responders here in GitHub are not relying as much as on the testing console when it comes to traffic verification - for that I would advise to double check with your dedicated account manager if you have one or our general support. Things we are pretty much relying mostly on are the SDK logs and might be good if you can check what's happening on that end for each of these builds you are mentioning. Regardless of your build (development vs. standalone), try putting SDK into sandbox environment, log level to verbose, run the app and pick up all the verbose logs SDK will produce - they should give us good enough idea of what's happening for that particular app run on your end. You can share them here if you want (feel free to omit any sensitive data you might not want to share) or try to email them to us if you prefer that way. One thing to keep in mind is that we need native Android and iOS logs.
2. Session callbacks are triggered whenever SDK tracks new session. It happens upon initial SDK launch after app has been installed and then whenever the time comes for new session to be tracked. SDK will trigger new session when app comes back to foreground after being outside of foreground for more than 30 minutes. The fact that you're not seeing callback being triggered in standalone build sounds similar to what you're noticing in first bullet point (lack of any data in testing console for those types of builds) and makes me wonder if SDK is running well in that build at all. Trying to see if any verbose logs are produced in those types of apps might tell us more.

**Comment by andrebiel** [comment]
Hey,

sorry for the late reply. Thanks for the detailed answer. I will create a non-development build but in sandbox mode and with the log level set to verbose. Afterward will come back here with the results!

At least it's something I can look forward to, so thanks again. 🚀

**Comment by uerceg** [comment]
hi @andrebiel,

Just following up on this one. Any updates in the meantime?

Cheers

**Comment by andrebiel** [comment]
Hey,

I’m sorry for the delay. Had to put this on halt for a moment but I’m back now. 

Will provide information soon. 

Thanks for asking 💯

**Comment by andrebiel** [comment]
Hey friendly helpers,

I was able to gather some information now.
Let's start with the exciting part - I printed out **all** available information.
To achieve that, I registered listeners for every event (as in your [example](https://github.com/adjust/react_native_sdk/blob/master/example/App.js). Furthermore, I built a screen showing the logs and the used configuration.

Unfortunately, no event is fired (and/or logged) at all:

<img width="186" alt="image" src="https://user-images.githubusercontent.com/91674154/184639626-a8b13339-1925-4a81-8809-b9cc7317972e.png">

You also can see that my environment is set to sandbox.
Is there any obvious mistake that you can see in my configuration?

To ensure I'm not missing something below is the full code of the initialization of Amplitude. You can also see that the function gets called because the configuration logging happens in the last line (and you can see the output in the screen).

```
export const init = (log: TrackingInitOptions["logger"]) => {
  const adjustConfig = new AdjustConfig(
    getEnv().adjustAppToken,
    getAdjustEnv()
  );

  adjustConfig.setLogLevel(AdjustConfig.LogLevelVerbose);

  adjustConfig.setAttributionCallbackListener(function (attribution) {
    log("Attribution callback received");
    log("Tracker token = " + attribution.trackerToken);
    log("Tracker name = " + attribution.trackerName);
    log("Network = " + attribution.network);
    log("Campaign = " + attribution.campaign);
    log("Adgroup = " + attribution.adgroup);
    log("Creative = " + attribution.creative);
    log("Click label = " + attribution.clickLabel);
    log("Adid = " + attribution.adid);
    log("Cost type = " + attribution.costType);
    log("Cost amount = " + attribution.costAmount);
    log("Cost currency = " + attribution.costCurrency);
  });
  adjustConfig.setEventTrackingSucceededCallbackListener(function (
    eventSuccess
  ) {
    log("Event tracking succeeded callback received");
    log("Message: " + eventSuccess.message);
    log("Timestamp: " + eventSuccess.timestamp);
    log("Adid: " + eventSuccess.adid);
    log("Event token: " + eventSuccess.eventToken);
    log("Callback Id: " + eventSuccess.callbackId);
    log("JSON response: " + eventSuccess.jsonResponse);
  });
  adjustConfig.setEventTrackingFailedCallbackListener(function (eventFailed) {
    log("Event tracking failed callback received");
    log("Message: " + eventFailed.message);
    log("Timestamp: " + eventFailed.timestamp);
    log("Adid: " + eventFailed.adid);
    log("Event token: " + eventFailed.eventToken);
    log("Callback Id: " + eventFailed.callbackId);
    log("Will retry: " + eventFailed.willRetry);
    log("JSON response: " + eventFailed.jsonResponse);
  });
  adjustConfig.setSessionTrackingSucceededCallbackListener(function (
    sessionSuccess
  ) {
    log("Session tracking succeeded callback received");
    log("Message: " + sessionSuccess.message);
    log("Timestamp: " + sessionSuccess.timestamp);
    log("Adid: " + sessionSuccess.adid);
    log("JSON response: " + sessionSuccess.jsonResponse);
  });
  adjustConfig.setSessionTrackingFailedCallbackListener(function (
    sessionFailed
  ) {
    log("Session tracking failed callback received");
    log("Message: " + sessionFailed.message);
    log("Timestamp: " + sessionFailed.timestamp);
    log("Adid: " + sessionFailed.adid);
    log("Will retry: " + sessionFailed.willRetry);
    log("JSON response: " + sessionFailed.jsonResponse);
  });
  adjustConfig.setDeferredDeeplinkCallbackListener(function (uri) {
    log("Deferred Deeplink Callback received");
    log("URL: " + uri.uri);
  });
  adjustConfig.setConversionValueUpdatedCallbackListener(function (
    conversionValue
  ) {
    log("Conversion value updated callback recveived");
    log("Conversion value: " + conversionValue.conversionValue);
  });

  Adjust.create(adjustConfig);
  log(`AdjustConfig: ${JSON.stringify(adjustConfig)}`);
};

```

Thanks in advance.

Andre

**Comment by uerceg** [comment]
Hey Andre,

Thanks for the info.

Hm. 🤔 Wondering why stringifying `AdjustConfig` didn't say anything about [`appToken`](https://github.com/adjust/react_native_sdk/blob/master/index.js#L242) value. Would it be possible to do the following:

1. Uninstall your app from test device (just for sake of having SDK start from newly installed state of app).
2. Install the app on your test device with above described SDK setup inside of it and run it.
3. Pick up all the logs from your app (I'm mostly interested in native iOS SDK logs which all have `[Adjust]` tag when printed) and send them over.

I see that you are using Xcode as well (vs. just running your app from RN CLI), so you can easily run the app from there and pick up all the logs which get printed when running the app. In case you are not using Xcode and are running app via RN CLI, you can always start macOS Console app, find your app's process and filter to show only those logs to pick them up.

In case data contained in there is sensitive, feel free to omit any sensitive info. If you're still not comfortable with posting those logs here, feel free to fire me an email with them (you can find my email in profile description).

**Comment by andrebiel** [comment]
I think that was a good hint 👍 (the token one)

Since we are getting the token from an env file, I wondered if that was the problem.

The emulator build looked good. I will give it a try and come back with the results.

Thanks again.

Will report back and hopefully close this issue.

**Comment by andrebiel** [comment]
We are now able to track installs. It was a problem with the *.env file, which ended up on a missing token. Thanks for helping out on this one. ❤️
