### ISSUE TITLE
react-native-adjust has been ignored because it contains invalid configuration dependency.platforms.ios.podspecPath

### ISSUE THREAD

**Issue by yahyamokaied** [adjust/react_native_sdk#188]
Package react-native-adjust has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.podspecPath" is not allowed

React Native 0.69.1

**Comment by namini40** [comment]
@yahyamokaied take a look at [this](https://stackoverflow.com/questions/32581986/cocoa-podspec-and-path-for-dependency)

**Comment by uerceg** [comment]
Hey @yahyamokaied,

Sorry for delay in replying. This sounds like an issue which [this PR](https://github.com/adjust/react_native_sdk/pull/186) addressed and which we have just added to our [latest v4.31.0 release](https://github.com/adjust/react_native_sdk/releases/tag/v4.31.0).

If you can give it a shot and let us know if that fixed your issue, would be great.

**Comment by uerceg** [comment]
In case the issue is still around (also make sure to give [latest version](https://github.com/adjust/react_native_sdk/releases/tag/v4.32.0) a shot), feel free to comment / reopen.

Cheers
