### ISSUE TITLE
How to test generated deeplink in debug mode for iOS?

### ISSUE THREAD

**Issue by enestatli** [adjust/react_native_sdk#189]
Whenever I open the link it redirects me to the AppStore, what I need is to open already installed app.

**Comment by uerceg** [comment]
Hi @enestatli,

Did you check the [deep linking](https://github.com/adjust/ios_sdk#deep-linking) chapter in README and have set up everything like described in there?

**Comment by uerceg** [comment]
Hey @enestatli,

Thanks for the link. Does it work now for you if you do follow the instructions from the chapter, or still not?

**Comment by enestatli** [comment]
Hey @uerceg,

I will test and let you know once we followed the instructions in the chapter

**Comment by enestatli** [comment]
@uerceg Hello, 

Still no luck on this issue.

**Comment by enestatli** [comment]
Hello @uerceg 

We forgot to add "apple-app-site-association" file to our web server. After adding, everything works fine.

**Comment by NancyGarg98** [comment]
> apple-app-site-association

Hi Can u help me here pls?
And let me know where you added it?

**Comment by enestatli** [comment]
> > apple-app-site-association
> 
> @enestatli 
> 
> Hi Can u help me here pls?
> And let me know where you added it?

Hello, backend guy was responsible for this, as far as I remember you need to just drag and drop your AASA file to your server with proper endpoint. Please refer to Apple documentation
