### ISSUE TITLE
Error while doing pod install

### ISSUE THREAD

**Issue by BerkD145** [adjust/react_native_sdk#191]
I was using the version 4.29.6 but suddenly it started to give this error : 
```
[!] CocoaPods could not find compatible versions for pod "Adjust":
  In Podfile:
    react-native-adjust (from `../node_modules/react-native-adjust`) was resolved to 4.31.0, which depends on
      Adjust (= 4.31.0)

None of your spec sources contain a spec satisfying the dependency: `Adjust (= 4.31.0)`.


```
I bumped up the version to 4.31.0 but still getting this error. I started developed recently. And I notice 4.31.0 is released very recently

**Comment by uerceg** [comment]
Hi @BerkD145,

Thank you for reporting this. We'll take a look and keep you posted.

**Comment by uerceg** [comment]
Hi @BerkD145,

Hm. We were unable to reproduce this on our end. We tried adding our latest SDK directly into a new React Native app and also tried to upgrade our SDK 4.29.6 inside of the existing app to latest version 4.31.0 (and ran `pod update` after npm package update) and everything worked just fine. 🤔 

Can you maybe try to deintegrate and re-add CocoaPods to your app project to see if things will work after that?

```
pod deintegrate
pod install
```

**Comment by uerceg** [comment]
In case the issue is still around (also make sure to give [latest version](https://github.com/adjust/react_native_sdk/releases/tag/v4.32.0) a shot), feel free to comment / reopen.

Cheers
