### ISSUE TITLE
Fail to build using Xcode 14.0

### ISSUE THREAD

**Issue by LucBarbier-tech** [adjust/react_native_sdk#193]
It seems you have an error in the podspecs
https://github.com/adjust/react_native_sdk/blob/fcf3559c3e0567fea1f1e42b71489062133a9f9d/react-native-adjust.podspec#L22

This issue explain it better than i could do => https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

But in short you need to replace 
`s.dependency 'React'` with `s.dependency 'React-Core'`

**Comment by uerceg** [comment]
Hey @LucBarbier-tech,

Thank you for reporting this. We have added the change in our [latest release](https://github.com/adjust/react_native_sdk/releases/tag/v4.32.0). If you can give it a shot and let us know if it fixed your issue, would be great.

Looking forward to hearing back from you.

Cheers
