### ISSUE TITLE
Used in China

### ISSUE THREAD

**Issue by chenyanji** [adjust/react_native_sdk#20]
In China, whether you will file the domain name, or will be restricted access, such as WeChat on

**Comment by uerceg** [comment]
Hi @chenyanji,

I didn't quite understand your message. What seems to be an issue?

**Comment by chenyanji** [comment]
@uerceg Can you use your product in China?

**Comment by uerceg** [comment]
@chenyanji

It is possible, but for more information on that topic please write an email to our support team to get more detailed information. 

support@adjust.com

Cheers
