### ISSUE TITLE
Track AppLovin MAX ad revenue

### ISSUE THREAD

**Issue by amsdamsgram** [adjust/react_native_sdk#209]
Hi,

We are implementing AppLovin MAX mediation on our React Native app.
To track the ad revenue in Adjust, should we just specify the source in `trackAdRevenue()` method like `trackAdRevenue(AdjustConfig.AdRevenueSourceAppLovinMAX)` or do we have to also set a payload?

If we need to set a payload, what is the definition expected for it?

I'm little bit confused by the [implementation of this method](https://github.com/adjust/react_native_sdk/blob/master/index.js#L54-L62):

Thank you for your help

**Comment by amsdamsgram** [comment]
Ok, I think I found my answer, we just need to specify the source and the rest is set up on Adjust platform according to this [documentation](https://help.adjust.com/en/article/applovin-max).

**Comment by uerceg** [comment]
Hi @amsdamsgram,

I am not sure what answer did you find, but I don't think that so far we have officially released any docs around SDK to SDK ad revenue tracking for any of the ad revenue sources for React Native platform.

In theory, if you do have a way to obtain ad revenue data from MAX impression callback in React Native, what you should do is something like this (code you'll see is part of our test app we use for end to end testing, but hopefully concept behind the API usage should be understandable from there): https://github.com/adjust/react_native_sdk/blob/master/test/app/command_executor.js#L797-L873

In case some things are still not clear and you have further questions, feel free to ping.

**Comment by amsdamsgram** [comment]
Hi,

I can confirm you that the ad revenue is automatically sent to Adjust from MAX SDK on React Native as we are seeing ad revenue on Adjust and we didn't do anything on our side.

**Comment by uerceg** [comment]
Hi @amsdamsgram,

And thank you for getting back on this one. That's actually pretty odd because neither is our SDK automatically subscribing to MAX SDK to obtain this data from their end or vice versa. Can it be that maybe you have this enabled on the account level so that we are pulling ad revenue data from MAX server side?

**Comment by uerceg** [comment]
In case there's still some open question(s) on this topic, feel free to comment / reopen. Closing this one.

Cheers
