### ISSUE TITLE
When do we get invalid signature for an install?

### ISSUE THREAD

**Issue by AppalaNaidu01** [adjust/react_native_sdk#221]
This info is stored against my ADID post installing the app on my testing device. When do this happen? Does this effect the `deferred deep link` listener?

It is the same when installed from XCode and Microsoft AppCenter.

<img width="615" alt="Screenshot 2023-10-30 at 5 27 34 PM" src="https://github.com/adjust/react_native_sdk/assets/66260142/ddb11e24-85d8-4a4a-8410-6f1279cdbb30">

**Comment by uerceg** [comment]
Hey @AppalaNaidu01,

Sorry for a bit of delay in replying to this one. I hope that you managed to solve this issue in the meantime, but in case it's still an issue for you, my advice would be to ping your dedicated account manager in case you have one, or if not, feel free to write about this issue to support@adjust.com and you'll be directed right people to help you with this issue which is not in scope of work of us who usually reply to GitHub SDK issues.

Cheers
