### ISSUE TITLE
Compilation failed 

### ISSUE THREAD

**Issue by VivekGoplan-Vivek** [adjust/react_native_sdk#226]
Am getting below error. while run the **react-native run-android** command. Pls find the attached image.

Java version: java 13.0.2 
![image](https://github.com/adjust/react_native_sdk/assets/137562731/837ed56c-5e64-4468-b7ed-fbf0636173e0)

"react-native-adjust": "^4.35.1",

**Comment by uerceg** [comment]
Hey @VivekGoplan-Vivek,

Sorry for a bit of delay on this one and thank you very much for reporting this. We have just shipped [v4.37.1](https://github.com/adjust/react_native_sdk/releases/tag/v4.37.1) update which should hopefully address this issue.

If you can give it a shot and let us know if it fixed the issue for you or not, that would be great.

Looking forward to hearing back from you.

Cheers

**Comment by VivekGoplan-Vivek** [comment]
@uerceg Yes, it is fixed. Thanks
