### ISSUE TITLE
setFbAppId support

### ISSUE THREAD

**Issue by Minishlink** [adjust/react_native_sdk#228]
Hello,

Will setFbAppId be added to the SDK? Is it something that will work only on Android, or also on iOS?

Thanks

**Comment by uerceg** [comment]
Hey @Minishlink,

We have just shipped [v4.37.0](https://github.com/adjust/react_native_sdk/releases/tag/v4.37.0) update where we have added this feature to React Native SDK. It's added just for sake of adding support for Meta install referrer, which is the Android platform feature only.

In case you have any further question(s), feel free to comment / reopen.

Cheers
