### ISSUE TITLE
Version 3.35.1 of the adjust signature library is not available

### ISSUE THREAD

**Issue by jleprinc** [adjust/react_native_sdk#256]
When building from a react native project on Android, I get an error that the adjust signature library is not available,

<img width="997" alt="Screenshot 2024-12-05 at 17 47 45" src="https://github.com/user-attachments/assets/caa05450-2f57-4265-b923-17560c5f19d8">

The issue may due to the package already released (4 hours ago) but not available yet on the maven repository. Is there a way to avoid having a build error everytime a new version is deployed?

Version of adjust: 5.0.1
Adjust signature library: v3.35.1

**Comment by uerceg** [comment]
Hey @jleprinc,

Sorry for the inconvenience, the update 3.35.2 has been shipped and should hopefully be available to address this issue. We'll keep you posted.

**Comment by uerceg** [comment]
Hello @jleprinc,

Can you give it another try? It should hopefully be fixed now with 3.35.2.

Looking forward to hearing back from you.

**Comment by erenatalay** [comment]
> Hello @jleprinc,
> 
> Can you give it another try? It should hopefully be fixed now with 3.35.2.
> 
> Looking forward to hearing back from you.

Where do we need to change the version of adjust-android-signature-3.35.1.jar.

**Comment by uerceg** [comment]
If it didn't get automatically pulled just when trying to rebuild your current Adjust React Native SDK, then it might have been the same issue as reported in native Android repo.

We will release an SDK update in the next couple of hours that should address this issue. I'll keep you posted.

**Comment by uerceg** [comment]
Hey @jleprinc, @erenatalay,

We have just shipped the [v5.0.3](https://github.com/adjust/react_native_sdk/releases/tag/v5.0.3) update which should hopefully address this issue. Looking forward to hearing back from you on whether it fixes this issue for you or not.

**Comment by erenatalay** [comment]
> Hey @jleprinc, @erenatalay,
> 
> We have just shipped the [v5.0.3](https://github.com/adjust/react_native_sdk/releases/tag/v5.0.3) update which should hopefully address this issue. Looking forward to hearing back from you on whether it fixes this issue for you or not.

problem solved thank you very much.

**Comment by uerceg** [comment]
And thank you very much for the feedback. Sorry one more time for the yesterday's inconvenience.

**Comment by jleprinc** [comment]
Problem solved indeed, thanks for the reactivity
