### ISSUE TITLE
Expo/CRNA app

### ISSUE THREAD

**Issue by appjitsu** [adjust/react_native_sdk#31]
Do Expo/CRNA apps need to be ejected to use this sdk?

**Comment by uerceg** [comment]
Hi @appjitsu 

To be honest, we never tested our React Native SDK with Expo/CRNA toolchain, so we do not know. Currently we are only developing and testing our SDK with intention to support "pure" react native app development.

In case you manage to make it work with Expo/CRNA app, feel free to share your discovery with us or if change that SDK needs to suffer in oder to support that is something you figure out on that quest, feel free to submit even PR for it and we would be glad to review it and consider making maybe better support for that with our plugin, but currently those things are not on our roadmap.

Cheers

**Comment by appjitsu** [comment]
![simulator screen shot - iphone x - 2018-03-12 at 13 18 26](https://user-images.githubusercontent.com/10903600/37301871-e0e10dd8-25f7-11e8-9128-7c15cab401e2.png)

const adjustConfig = new AdjustConfig(ADJUST_APP_TOKEN, AdjustConfig.EnvironmentSandbox);
Adjust.create(adjustConfig);

**Comment by appjitsu** [comment]
Is there a web services implementation?

**Comment by uerceg** [comment]
To be honest, not sure how to troubleshot this kind of app which we don't really have support for. If you maybe have instructions how to build an example app in which we can reproduce this issue and see maybe how to make the SDK work, please share the steps in here and we'll give our best to take a look at it.

Also, Adjust platform can be used in your app without SDK, but as a S2S (server to server), but for more information on that, it would be the best to contact our support by sending email to support@adjust.com.

**Comment by appjitsu** [comment]
I had to eject the app and follow the setup guide. It's all working now. Thanks!
