### ISSUE TITLE
IOS installation

### ISSUE THREAD

**Issue by Tix6** [adjust/react_native_sdk#34]
Hello,

I tried to install your react-native sdk on iOS, but i encountered some issues on both of your solutions.

with RN link:
```
Scanning folders for symlinks in /Users/***/***/node_modules (15ms)
rnpm-install info Android module react-native-adjust is already linked
rnpm-install info Linking react-native-adjust ios dependency
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined
Please file an issue here: https://github.com/facebook/react-native/issues
```

with CocoaPods:
```
** BUILD FAILED **

The following build commands failed:
        CompileC /Users/***/***/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-adjust.build/Objects-normal/x86_64/AdjustEventEmitter.o /Users/***/***/node_modules/react-native-adjust/ios/AdjustEventEmitter.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/***.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/***.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Environment:
```
  OS: macOS High Sierra 10.13.2
  Node: 9.2.1
  Yarn: 1.7.0
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0
```

Best regards.

**Comment by Tix6** [comment]
I fixed the previous react-native link error:

I put a comment on the bottom of my Podfile
```
  # Add new pods below this line
```

Thus the linking works well but i got another error from the simulator:

```
Native module cannot be null
```

**Comment by uerceg** [comment]
@Tix6 

First error seems like some React Native related issue. Did you check this thread https://github.com/facebook/react-native/issues/16774? Especially this comment https://github.com/facebook/react-native/issues/16774#issuecomment-350999013 which says about potential issues in attempting to use React Native plugins with both, link and Cocoapods.

As far as `Native module cannot be null` error, seems like a result of linking error according to this thread https://github.com/zo0r/react-native-push-notification/issues/160.

How are you adding Adjust SDK at the end to your iOS app - via `npm` repo or Cocoapods?

**Comment by Tix6** [comment]
@uerceg 

> First error seems like some React Native related issue. Did you check this thread facebook/react-native#16774? Especially this comment facebook/react-native#16774 (comment) which says about potential issues in attempting to use React Native plugins with both, link and Cocoapods.

Sure! Like i said in my previous response, this point is fixed.

So for now, when i use `react-native link`, the android part works well, but nothing change for iOS except the podfile which is updated with this line:
```
pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'
```
then, after building, the `Native module cannot be null` error is displayed.

**with CocoaPods**

```
In file included from /Users/***/***/node_modules/react-native-adjust/ios/AdjustEventEmitter.m:9:
/Users/***/***/node_modules/react-native-adjust/ios/AdjustEventEmitter.h:14:9: fatal error: 'RCTEventEmitter.h' file not found
#import <RCTEventEmitter.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.


** BUILD FAILED **


The following build commands failed:
        CompileC /Users/***/***/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-adjust.build/Objects-normal/x86_64/AdjustEventEmitter.o /Users/***/***/node_modules/react-native-adjust/ios/AdjustEventEmitter.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/***.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/***.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by uerceg** [comment]
I am still unable to reproduce this issue. I tested adding our SDK to RN app via Cocoapods and seems to be working just well. Here's how my test looked like:

Create dummy app:
```
react-native init AdjustPodTest
```

Install NPM stuff:
```
cd AdjustPodTest
npm install
```

Add Adjust SDK:
```
npm install react-native-adjust --save
```

Add Podfile to my iOS app so that I can add Adjust SDK via Pods:

```
platform :ios, '9.0'

target 'AdjustPodTest' do

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'DevSupport',
  'RCTText',
  'RCTAnimation',
  'RCTImage',
  'RCTNetwork',
  'RCTVibration'
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'

end
```

Install Pods:
```
pod install
```

Run app with Adjust SDK inside:
```
cd ..
react-native run-ios
```

And app starts without any issues and uses Adjust SDK.

If I try to run link command after this:
```
react-native link
```
I get following:
```
➜  AdjustPodTest react-native link
Scanning folders for symlinks in /Users/uerceg/Projects/ReactNative/AdjustPodTest/node_modules (16ms)
rnpm-install info Platform 'ios' module react-native-adjust is already linked
rnpm-install info Linking react-native-adjust android dependency
rnpm-install info Platform 'android' module react-native-adjust has been successfully linked
```

My React Native version:
```
react-native --version
react-native-cli: 2.0.1
react-native: 0.56.0
```

Can you please tell me what I am doing differently than you so that I could actually reproduce this issue?

**Comment by Tix6** [comment]
In order to reproduce my issue, you should use the same react-native version than me. (0.51 vs 0.56)

In my opinion it looks like a header issue, i've got the same issue with another native library which has fixed it with this PR: https://github.com/react-native-community/react-native-text-input-mask/commit/1e342e7781853b3b27abebabf5067955fe5fade4

**Comment by uerceg** [comment]
Thanks @Tix6, will run tests with RN 0.51 and keep you posted.

**Comment by uerceg** [comment]
Hey @Tix6 

I am definitely unable to reproduce this with `react-native@0.51.0`. I have repeated steps described couple of comments above just with usage of version you have been using and I got same outcome from the test.

If you have any idea what else to try in order to reproduce this issue, please let us know.

**Comment by Tix6** [comment]
Finally i suceeded the installation ! 😄 

I had to use `pod install` instead of just RN-link which made nothing on my projet (probably because of my pods or my workspace project), then make a couple of adjustments :

- Add `# Add new pods below this line` on the bottom of the Podfile.
- Add
```
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'DevSupport',
      'RCTText',
      'RCTAnimation',
      'RCTImage',
      'RCTNetwork',
      'RCTVibration'
    ]
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
```
In addition of the line: `pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'`.
- Comment the `use_frameworks!` line in the Podfile. ( => Yoga error )
- Install pods.
- Then use `react-native link react-native-adjust`

**Comment by uerceg** [comment]
Good news! Glad it worked for you. Feel free to ping us in case you need any other assistance. Cheers! 🍺
