### ISSUE TITLE
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'module_adjust.create')]

### ISSUE THREAD

**Issue by masonworkq** [adjust/react_native_sdk#36]
It works well on iOS side, but I am getting error on Android.

settings.gradle
include ':react-native-adjust'
project(':react-native-adjust').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-adjust/android')

mainapplication.java

...
import com.adjust.nativemodule.AdjustPackage;

public class MainApplication extends ExpoApplication {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        // new MainReactPackage(),
            new VectorIconsPackage(),
            new PinchPackage(),
            new LinearGradientPackage(),
            new RNIapPackage(),
            new AdjustPackage()
    );
  }
...

// adjust sdk
    const adjustConfig = new AdjustConfig (
      ADJUST_APP_TOKEN,
      AdjustConfig.EnvironmentProduction
    );
    Adjust.create (adjustConfig);

**Comment by uerceg** [comment]
Hi @masonworkq 

Seems like you're making an Expo app? I don't think that native plugins (like ours SDK is) work with Expo apps. According to their page https://docs.expo.io/versions/latest/introduction/faq:

```
But no native modules...

The most limiting thing about Expo is that you can't add in your own native modules without detaching and using ExpoKit. Continue reading the next question for a full explanation.
```

**Comment by masonworkq** [comment]
Hi @uerceg 
Thanks for your reply.

I checked that link, but iOS side works fine.

**Comment by uerceg** [comment]
Good to know, thanks on that info, but I think that in general Expo still doesn't support native modules and due to that fact, I think our SDK won't work. Seems like Android platform has issues with that fact.

In order for SDK to work, I think that you would need to eject from Expo environment or have your app project created with `react-native init` command.

**Comment by masonworkq** [comment]
Alright.
Thanks for your help.
