### ISSUE TITLE
How do I completely uninstall this library?

### ISSUE THREAD

**Issue by zeckdude** [adjust/react_native_sdk#37]
I don't see any instructions in the README about how to remove the library. I removed the Podfile code and thought that was all that is needed. Now I still have a bunch of references in my `.pbxproj` file.

**Comment by uerceg** [comment]
@zeckdude 

After removing Adjust pod entry from your Podfile, which command did you run? Did you `unlink` and `uninstall` our React Native plugin from your React Native project?

**Comment by uerceg** [comment]
@zeckdude Any luck with this issue?

**Comment by uerceg** [comment]
Feel free to reopen an issue in case you still need help on this one. Cheers!
