### ISSUE TITLE
Are there any plans to update buildToolsVersion?

### ISSUE THREAD

**Issue by shercoder** [adjust/react_native_sdk#38]
Since all existing Android apps have to support `targetSDKVersion: 26`, ReactNative 0.56 updates the targetSDKVersion along with `buildToolsVersion` as well. All libraries need to be updated to support at least buildToolsVersion 25. I would suggest matching it with versions set in ReactNative.

https://github.com/facebook/react-native/blob/v0.56.1/ReactAndroid/build.gradle#L249

Are there any plans to do this? 

FYI, New apps deadline was August and any existing apps must update to targetSDKVersion 26 by November if they want to push any updates.

**Comment by uerceg** [comment]
Hi @shercoder

Thanks for the info. Yes, we will include this into our upcoming v4.15.0 release. Will keep you posted in here. 

Cheers

**Comment by shercoder** [comment]
@uerceg Thanks for the quick reply.

Do you know the ETA for 4.15.0?

**Comment by uerceg** [comment]
Not strict one, but we’ll aim to have it live in next 2 weeks. Hope that’s okay with your plans.

**Comment by uerceg** [comment]
Hey @shercoder 

Please feel free to give latest SDK version a shot (https://github.com/adjust/react_native_sdk/releases/tag/v4.15.0), Android SDK and build tools should have been updated to minimum advised level 26.

In case you encounter any other issues regarding this topic, feel free to reopen the issue.

Cheers!

**Comment by shercoder** [comment]
Will do. Thanks for the update. and apologies for the late reply as I was OOO for a while.
