### ISSUE TITLE
Error building the project

### ISSUE THREAD

**Issue by BologaMarius** [adjust/react_native_sdk#39]
![screen shot 2018-09-27 at 13 58 58](https://user-images.githubusercontent.com/11151638/46141989-32374f00-c25e-11e8-9707-57ad4e3c25e9.png)

I want to make a beta build of the app and I receive the above mentioned error.  On the debug mode this works fine. Any ideas?

Versions:
npm: 5.6.0
react-native-cli: 2.0.1
react-native: 0.52.3
Platform: iOS

**Comment by uerceg** [comment]
Hi @BologaMarius 

Sorry for a bit delayed answer. Which Adjust SDK version are you using and how are you adding it to your iOS app - are you linking it or using via Cocoapods?

**Comment by BologaMarius** [comment]
Hi @uerceg 
I've managed to solve this error by manually linking the framework. Neither installing the library by linking or via Cocoapods worked. You should update the integration steps in the documentation.
Thanks
