### ISSUE TITLE
Typings for Typescript users

### ISSUE THREAD

**Issue by luisnaranjo733** [adjust/react_native_sdk#40]
This lib is missing typings. After taking a quick peek at the source, it seems like it would be pretty easy to add given how straightforward the API is.

**Comment by luisnaranjo733** [comment]
Here is an example that I used to unblock myself in a local adjust.d.ts file. It'd be cool if this could be iterated on and shipped with the npm package so that TS users don't have to do this themselves

**Comment by uerceg** [comment]
Hey @luisnaranjo733 

Thanks for the idea and the advices. We'll definitely check it out and try to add support for TypeScript in our future releases.

Will keep you posted.

Cheers!

**Comment by uerceg** [comment]
Added to our backlog, we should hopefully address this soon. Closing the issue, thanks for the suggestion, we'll keep you posted on the progress.
