### ISSUE TITLE
No visible @interface for 'ADJEvent' declares the selector 'setCallbackId:'

### ISSUE THREAD

**Issue by rastegars** [adjust/react_native_sdk#44]
After updating to 4.15.0, I'm getting this error:
`No visible @interface for 'ADJEvent' declares the selector 'setCallbackId:'` in xcode.

**Comment by uerceg** [comment]
Are you adding iOS native part via Pods maybe?

**Comment by rastegars** [comment]
> Are you adding iOS native part via Pods maybe?

Yes, I'm.

**Comment by uerceg** [comment]
Make sure that you update Pods as well with each SDK update.

**Comment by rastegars** [comment]
Thanks, I updated Pods and the issue was resolved.

**Comment by uerceg** [comment]
Great, thanks for letting us know!

Cheers!
