### ISSUE TITLE
Add instructions on how to ensure SDK is properly installed

### ISSUE THREAD

**Issue by econner** [adjust/react_native_sdk#45]
It'd be helpful if there were some instructions on how to ensure that once I've installed the SDK it is correctly reporting to Adjust.

Right now there are instructions to install the SDK and then there's a wall of text of additional things that need to be done specific to Android and iOS, but I don't even know if the basic install can communicate with Adjust.

**Comment by uerceg** [comment]
@econner Thanks for the advice. Makes sense. Quick tip for now would be: While testing in sandbox mode, set log level to verbose and check out logs, they should be pretty self explainatory. Android ones you can filter by looking for LogCat tag “Adjust”. 

But fair point. We will look to add more detailed explanation on this topic in README. :+1:

**Comment by cyberdude** [comment]
If I don't see any logs is that there's something wrong right?

**Comment by uerceg** [comment]
We're gonna be performing major SDK README cleanups in Q1 and Q2 of 2020 and this will be addressed in there. Closing the issue for now, but will ping you in here once new README is live.

@cyberdude I am not sure I understood your question?
