### ISSUE TITLE
Can't integrate Adjust react-native-sdk using pod

### ISSUE THREAD

**Issue by vicky462** [adjust/react_native_sdk#46]
I have added following line in pod file.
**pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'**
After pod installation i got "RCTEventEmitter.h file not found" error while run a project.
<img width="912" alt="screen shot 2018-10-23 at 7 06 50 pm" src="https://user-images.githubusercontent.com/36153973/47410087-4b122200-d782-11e8-87d6-16bf9d2dddd9.png">

I am using 
     "react": "^16.0.0",
    "react-native": "^0.50.3",
   "react-native-adjust": "^4.15.0",

**Comment by uerceg** [comment]
Hi @vicky462 

Not sure if issue is the same, but did you take a look at issue #34 from this comment (https://github.com/adjust/react_native_sdk/issues/34#issuecomment-403434908) on and tried the suggested solution from there?

**Comment by uerceg** [comment]
@vicky462 Closing this one under assumption that it's no longer an issue for you. In case issue is still there with latest SDK version available, please feel free to reopen the issue.

Cheers
