### ISSUE TITLE
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

### ISSUE THREAD

**Issue by vitorreis** [adjust/react_native_sdk#47]
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
>It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

You should probably update this

**Comment by uerceg** [comment]
Hi @vitorreis 

We have just released React Native SDK v4.17.0 update. If you can please check it out and let us know if it solves this issue for you. Looking forward to hear from you.

Cheers.

**Comment by uerceg** [comment]
In case this issue is not solved with latest SDK update, feel free to reopen the issue. Cheers.
