### ISSUE TITLE
How to test Deferred Deeplinking in Release Build + adjust production environment?

### ISSUE THREAD

**Issue by rrobbie1** [adjust/react_native_sdk#51]
Hi,

I was testing successful in the (android / ios Debug build + adjust sandbox environment)
=> reference : https://github.com/adjust/android_sdk/issues/360 

but, ( release build + adjust production environment + App Store beta version install ) is not working.
ex) * not release mode in store, only **beta** mode in store.
 android : https://play.google.com/apps/testing/com.noahclient.dev

How to test Deferred Deeplinking in (android/ios) Release Build + adjust production environment?

If you've seen success in development environment, are you surely successful in the release environment?

**Comment by uerceg** [comment]
@rrobbie

Are you using different package identifiers for these different builds? When it comes to testing this feature, you need to make sure that Android package ID you entered in dashboard matches your app's package ID. In this URL I see ".dev" suffix which might be something you are adding to this test build only?

**Comment by rrobbie1** [comment]
android app package name : ( com.noahclient.dev )

**Comment by uerceg** [comment]
@rrobbie1 

Did you manage to solve this issue and if yes, what was the solution?
