### ISSUE TITLE
Use api instead of implementation in build.gradle

### ISSUE THREAD

**Issue by smacgregor** [adjust/react_native_sdk#53]
Adjust 4.17 changed the compile keyword in [build.gradle](https://github.com/adjust/react_native_sdk/blob/master/android/build.gradle#L29) to implementation.  That should have been changed to api not implementation. Our react native project no longer compile after upgrading from 4.15 to 4.17. Locally patching the package to use api resolves the issue.

This was from:

https://github.com/adjust/react_native_sdk/issues/47

**Comment by uerceg** [comment]
Hi @smacgregor 

Interesting. Can you please provide us with compile time error details you are getting because of this?

**Comment by uerceg** [comment]
@smacgregor Any update on this one? I am curious to see what is exact error you're getting to try to understand why is there a need for usage of `api` keyword.

**Comment by uerceg** [comment]
Closing an issue due to inactivity, please feel free to reopen it in case any further discussion is needed. Cheers.
