### ISSUE TITLE
Error: AdjustReferrerReceiver does not exist in 4.17.0

### ISSUE THREAD

**Issue by shercoder** [adjust/react_native_sdk#55]
I'm getting the below error after updating the sdk from 4.15.0 to 4.17.0. Any idea what's going on here?

![image](https://user-images.githubusercontent.com/1681066/53207689-46069780-35e9-11e9-9c53-35de5f8d58a2.png)

**Comment by uerceg** [comment]
🤔 This is pretty weird. `AdjustReferrerReceiver.java` is class which is part of `com.adjust.sdk` package of our native Android SDK and is in there since forever in v4.x.y. Honestly, can't think of why is this happening. Did you manage to solve it in the meantime (sorry for a bit delayed answer) or is it still an issue for you?

**Comment by shercoder** [comment]
@uerceg It's still an issue. We had to revert back to 4.15.0 unfortunately. It's still an issue with 4.17.0.

**Comment by uerceg** [comment]
@shercoder Hm.

1. Which Gradle version are you using in your Android Studio project?
2. Which class in your app is actually trying to reference `AdjustReferrerReceiver`? That class in theory shouldn't be referenced unless you maybe have your own custom receiver class for `INSTALL_REFERRER` intent and are trying to ping ours from there. Is that the case in your app?

**Comment by shercoder** [comment]
@uerceg 

![image](https://user-images.githubusercontent.com/1681066/53511044-47661300-3a74-11e9-8f36-d4ce7656422a.png)

We have our custom receiver class that we have always used and been referencing `AdjustReferrerReceiver` from there for quiet a while now. Could that no longer be accessed?

**Comment by 2beens** [comment]
Hello @shercoder !
Do you still have this issue?
I have tried to reproduce your problem, created a new react native app and integrated our latest 4.17.0 SDK, and everything went fine and smooth.
But, judging from the first screenshot you provided, it seems that the whole `com.adjust.sdk` package is missing. Can you try to remove it completely, and install again?

**Comment by uerceg** [comment]
Hi @shercoder,

Any update on this one?

**Comment by rawrmaan** [comment]
Since the SDK isn't defined as a dependency in this library's `build.gradle`, but instead included as a `.jar` file, you need to add the following to your app's own `app/build.gradle` in order for `com.adjust.sdk` to resolve:

`implementation fileTree(include: ['*.jar'], dir: '../../node_modules/react-native-adjust/android/libs')`

**Comment by shercoder** [comment]
Hi guys, sorry about not replying here soon enough. I actually haven't had a chance to test it again, my priorities changed at work so could not get to this. I'll see if I can carve some time out next week to try this. I'm going to close this for now but reopen if others are having this issue as well.

**Comment by shercoder** [comment]
Hey guys, I just wanted to give an update on this. My teammate tried @rawrmaan's solution and it worked for us.

**Comment by shercoder** [comment]
@uerceg @rawrmaan so I have been think about this issue and came across something on the internet. I think there might be a better solution than manually adding the jar files. Although I haven't tried it but if you switch `implementation` to `api` here https://github.com/adjust/react_native_sdk/blob/master/android/build.gradle#L29, it will expose the underlying api of the jar files. `implementation` supposed to hide this whereas `api` exposes them.

Here is a really good read from Mindorks about this topic https://medium.com/mindorks/implementation-vs-api-in-gradle-3-0-494c817a6fa

**Comment by apoorva-techie** [comment]
> Since the SDK isn't defined as a dependency in this library's `build.gradle`, but instead included as a `.jar` file, you need to add the following to your app's own `app/build.gradle` in order for `com.adjust.sdk` to resolve:
> 
> `implementation fileTree(include: ['*.jar'], dir: '../../node_modules/react-native-adjust/android/libs')`

This needs to be updated in the latest docs as well!! Would save a lot of time!

**Comment by uerceg** [comment]
Hey guys, sorry for slow reply in here. Thanks for your findings and advices, will be addressed in next RN SDK update! Will keep you posted.

**Comment by piraka9011** [comment]
@uerceg we are still seeing this in RN version 4.35.1
Will this workaround be included in the official docs for awareness, or will there be a solution to automagically including the lib in the android build?
