### ISSUE TITLE
Event not getting listed on dashboard

### ISSUE THREAD

**Issue by Kiran0791** [adjust/react_native_sdk#57]
Hi,

The SDK is set up and i do see the version and the sdk enabled return true. And I have created an event and trying to log it using it s token as mentioned in the docs. But i don't find it on the dashboard. Not sure if is getting logged or no as u don't see any exceptions.

Kindly some one help me with this....

**Comment by uerceg** [comment]
Hi @Kiran0791 

Are you testing your app with SDK set to sandbox? If yes, are you checking sandbox traffic in our dashboard?

**Comment by Kiran0791** [comment]
> Hi @Kiran0791
> 
> Are you testing your app with SDK set to sandbox? If yes, are you checking sandbox traffic in our dashboard?

Yes. Sandbox mode is set and i tried to filter out the by sandbox under Deliverables.

**Comment by uerceg** [comment]
I am not up to date with this info (our official support team knows that), but after tracking even it actually takes some time for event to be displayed in dashboard, it's not immediate action. So not sure how long did you wait before checking, but I think it actually takes some time (maybe 10-ish minutes, not sure, maybe faster, but for this info better to check with support@adjust.com).

**Comment by Kiran0791** [comment]
> I am not up to date with this info (our official support team knows that), but after tracking event it actually takes some time for event to be displayed in dashboard, it's not immediate action. So not sure how long did you wait before checking, but I think it actually takes some time (maybe 10-ish minutes, not sure, maybe faster, but for this info better to check with [support@adjust.com](mailto:support@adjust.com)).

Its more than 2hrs. But am i finding my event  at the right place.

**Comment by uerceg** [comment]
It should definitely not take that long. Are you sure that your event was indeed tracked by SDK? Can you repeat the test case and check it again? Have SDK environment set to sandbox and log level to verbose. Do the event tracking action and check the logs if event was indeed successfully tracked. After that it should appear in dashboard. In case you are not sure what logs are saying, feel free to send them over (and remove any sensitive information if any in those logs).

**Comment by uerceg** [comment]
In case you are still facing issues on this topic, feel free to ping in here or simply send an email to your dedicated account manager or support@adjust.com.

Cheers
