### ISSUE TITLE
iOS install fails with `Native module cannot be null` 

### ISSUE THREAD

**Issue by alex-mironov** [adjust/react_native_sdk#58]
After installation of the Adjust, build fails with "Native module cannot be null." Linking seems to be fine:
```
 react-native link react-native-adjust
rnpm-install info Linking react-native-adjust ios dependency
rnpm-install info Platform 'ios' module react-native-adjust has been successfully linked
rnpm-install info Linking react-native-adjust android dependency
rnpm-install info Platform 'android' module react-native-adjust has been successfully linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project
```
Versions:
```
    "react-native": "0.57.7",
    "react-native-adjust": "^4.17.0",
```
Please suggest what could be wrong.

**Comment by amarnathsdr** [comment]
I had the same problem, I installed a previous version of adjust and it works on android

**Comment by amarnathsdr** [comment]
Yes me too, installed the version before the eventEmeter was added. and then had to make the link with iOS manually...

**Comment by uerceg** [comment]
Hi @alex-mironov 

Are you still facing this issue with 4.17.2 as well?

**Comment by mertkanu** [comment]
Hey @uerceg,
I'm having the same issue:

Versions:
```
"react-native": "0.58.4",
"react-native-adjust": "^4.17.2",
```

**Comment by mertkanu** [comment]
> Hey @uerceg,
> I'm having the same issue:
> 
> Versions:
> 
> ```
> "react-native": "0.58.4",
> "react-native-adjust": "^4.17.2",
> ```

I had to link iOS manually to make it work.

**Comment by shercoder** [comment]
I just tried installing this module via Cocoapods and I'm getting the same error. 
I added this to my Podfile: `pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'` and ran `pod install` which added `Adjust.framework` and `react-native-adjust.framework` under `Build Phases > Embed Pods Frameworks`

I am using version `4.18.1`, which is the latest as of this comment.

Does pod linking not work properly? Is this a known issue?

**Comment by uerceg** [comment]
@shercoder 

Hm. This wasn't reported to us until now. Is this still an issue for you?

I have just tried creating react native app from scratch, adding Adjust SDK to it and instead of linking it manually, added it to iOS app via Cocoapods. Same line like yours added to `Podfile`, `pod install` finished successfully and after opening iOS project's workspace, app built successfully.

**Comment by evglayton** [comment]
Had the same problem. I solved it by adding library manually.
https://facebook.github.io/react-native/docs/linking-libraries-ios

**Comment by uerceg** [comment]
Will close this one, but feel free to reopen/comment if issue is still happening with latest SDK version. Cheers.
