### ISSUE TITLE
Deferred deep linking doesn't launch the URL by default on android

### ISSUE THREAD

**Issue by StanislavMayorov** [adjust/react_native_sdk#61]
Hi. Deferred deep linking doesn't launch the URL by default on android.

We use deferred deep linking and default [setShouldLaunchDeeplink should be true](https://github.com/adjust/react_native_sdk#deferred-deep-linking-scenario). 
Steps:
- Remove app
- Forget devices in testing console
- Click on CLICK URL
- Install app

Result:
On android URL isnt opened in browser.
On ios URL is opened in safari as expected.
react-native-adjust 4.17.0.

**Comment by uerceg** [comment]
You can check the verbose SDK logs when testing this flow if attribution response is getting deep link information back from the backend. How does your test URL look like (feel free to omit any sensitive info from it, just interested in general content of it)?

**Comment by StanislavMayorov** [comment]
Test URL looks like this 
`https://app.adjust.com/{token}?deeplink={firebase.page.preview}`. I didn't check logs, but attribution and deferred deep worked in the app so it should be okay.

**Comment by uerceg** [comment]
So attribution callback gives you back information that install is attributed to `[token]` from your URL and SDK opens the `{firebase.page.preview}` as expected in iOS, but not in Android?

What is the `trackerToken` value you get in attribution callback when testing with Android? Is it `[token]` or some other?

**Comment by StanislavMayorov** [comment]
> So attribution callback gives you back information that install is attributed to `[token]` from your URL and SDK opens the `{firebase.page.preview}` as expected in iOS, but not in Android?

Yes, android sdk doesnt open `{firebase.page.preview}` in browser and attribution callback gives me back information that install is attributed.

> What is the `trackerToken` value you get in attribution callback when testing with Android? Is it `[token]` or something else?

`trackerToken` and `trackerName` is right on android. There is only one problem that link isnt opened in browser.

**Comment by uerceg** [comment]
I see. Well, thing with deferred deep linking is that our SDK will not try to open the link in browser. Deep link should usually contain scheme name at its beginning and that scheme should be associated with an activity in your app which knows how to handle it. So when deferred deep link arrives into SDK, SDK will try to "open" it. Translated into actual action in the app - it will launch activity which knows how to handle it.

SDK will get deferred deep link content from backend, translate it to `Uri` object and try to [open it](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-core/src/main/java/com/adjust/sdk/ActivityHandler.java#L1276). That attempt will invoke `startActivity` method on the `Context` object if there's any to be launched. If such activity is found and opened, content of the `Uri` object will be passed to it as part of `onCreate` or `onNewIntent` method (depends on your activity `launchMode` settings in manifest file).

**Comment by StanislavMayorov** [comment]
> SDK will get deferred deep link content from backend, translate it to `Uri` object and try to [open it](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-core/src/main/java/com/adjust/sdk/ActivityHandler.java#L1276). That attempt will invoke `startActivity` method on the `Context` object if there's any to be launched. If such activity is found and opened, content of the `Uri` object will be passed to it as part of `onCreate` or `onNewIntent` method (depends on your activity `launchMode` settings in manifest file).

In our app splash screen is opened when we get information from DeferredDeeplinkCallback. Could it be the reason?

**Comment by uerceg** [comment]
I am still not really sure what's going on in your app. Are you implementing `setDeferredDeeplinkCallbackListener` in it? If yes, what's happening in there (maybe you can share the code and omit sensitive parts)?

**Comment by StanislavMayorov** [comment]
Yes, we use `setDeferredDeeplinkCallbackListener`.
It's simplified part of our code. It's run before splash screen is hidden.
```
const adjustConfig = new AdjustConfig(key, __DEV__ ? AdjustConfig.EnvironmentSandbox : AdjustConfig.EnvironmentProduction);
adjustConfig.setAttributionCallbackListener((attribution) => {
  console.warn('attribution', attribution);
});

adjustConfig.setDeferredDeeplinkCallbackListener(deeplink => {
  console.warn('deeplink', deeplink);
});

Adjust.create(adjustConfig);
```

**Comment by uerceg** [comment]
Hi @StanislavMayorov 

Sorry for delay in here. Did you manage to figure out what was causing the issue?

What is `{firebase.page.preview}` in your case? Is it some URL (`http`/`https`)?

**Comment by StanislavMayorov** [comment]
I don't work at this project now so I can't add any details. You can close if you can't reproduce it.
We didn't resolve it. We disable setShouldLaunchDeeplink for ios and android. It was https URL.

**Comment by uerceg** [comment]
Thanks for your info, I was not really able to reproduce it, so too bad we can't get any more info. I will close it for now, but in case you encounter anything related to it (or anyone else), feel free to reopen it. Cheers!
