### ISSUE TITLE
When setting revenue, event is not listed.

### ISSUE THREAD

**Issue by witalobenicio** [adjust/react_native_sdk#73]
When we set a revenue and trackingId, the revenue is listed on dashboard but not the event.

**Comment by uerceg** [comment]
Hi @witalobenicio

In theory, if event was tracked by our SDK, you should see it in the dashboard as well (including attached revenue if any). One thing to keep in mind is that dashboard is not real time, so it might take few minutes before count increase for that event shows up in the dashboard. Also a thing to pay attention to is to make sure that you are checking proper traffic in the dashboard (meaning that if you are testing SDK and have it set to sandbox mode, you should take a look at sandbox traffic in the dashboard to see traffic from those test runs).

Did you manage to see event being tracked?

**Comment by witalobenicio** [comment]
@uerceg yep, it took a while to see revenue, but after some time it got "linked" to the events.
