### ISSUE TITLE
Crash when accessing pushToken on iOS

### ISSUE THREAD

**Issue by oisu** [adjust/react_native_sdk#81]
Adjust.create() fails due to
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI isEqualToString:]: unrecognized selector sent to instance 0x112018800'`
when accessing `pushToken` here.

It works if comment out this line on iOS module side.
https://github.com/adjust/react_native_sdk/blob/557c5b746dab98b202da1760f850979b182fb9d2/ios/Adjust/ADJActivityHandler.m#L689

I'm Wondering invalid value is saved or failed to get value via UserDefaults.
How to deal with this issue?

react-native info:
```
System:
    OS: macOS 10.15
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 5.20 GB / 40.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

**Comment by uerceg** [comment]
Hi @oisu 

Which Adjust SDK version are you using?

**Comment by oisu** [comment]
@uerceg Thanks for the reply.
I tried react-native-adjust `4.18.2` and `4.17.2`.

**Comment by uerceg** [comment]
@oisu 

And are you facing the same issue with both versions? How does the push token value look like when you pass it to Adjust SDK from your RN app? If you can debug your app where you are reproducing this issue, can you tell me what are the values of `deviceToken` and `pushToken` variables from `ADJActivityHandler.m` file before you call to `[selfI setPushToken:pushToken];`?

**Comment by oisu** [comment]
@uerceg 
Yes, with both versions.

And the values of `deviceToken` and `pushToken` are look nil when I put a breakpoint right before the `setPushToken` line which causes crash.

But I found that `selfI` also looks `nil` prior to that. Is this the root cause?

<img width="791" alt="Screen Shot 2020-01-08 at 15 59 22" src="https://user-images.githubusercontent.com/4394282/71957099-2774b380-3230-11ea-89b2-6eaf36fafc7a.png">

**Comment by oisu** [comment]
@uerceg Do you have any idea? We've gotten stuck and it's hard for our app to use Adjust SDK.

**Comment by nonelse** [comment]
if it works to set an empty string, it's ok to do it instead of passing nil. It's the same as not setting any value

**Comment by oisu** [comment]
Just setting empty string on the JavaScript side doesn't work.
The above is a hacky solution and requires us to modify the SDK before building.

**Comment by uerceg** [comment]
Hi @oisu 

Can you describe a scenario in which you're able to reproduce this crash? I'm interested in where are you setting push token value in your RN app (and with which value) and where are you starting the SDK.

**Comment by uerceg** [comment]
@oisu 👋 Any update on this one?

**Comment by uerceg** [comment]
If needed and still an issue with latest SDK version, feel free to comment/reopen. Cheers.
