### ISSUE TITLE
React Native SDK Release Containing IOS 4.21.3

### ISSUE THREAD

**Issue by smacgregor** [adjust/react_native_sdk#86]
Any chance we can get a release pushed to npm that updates the IOS pod spec to 4.21.3 to match the latest release IOS SDK release on https://github.com/adjust/ios_sdk/releases.

For background we just updated from RN Adjust 4.18.2 to 4.21 and started seeing the following crash:

```
EXC_BAD_ACCESS Attempted to dereference garbage pointer 0x38. 
    /usr/lib/system/libdispatch.dylib __dispatch_source_set_handler
    NewWordsWithFriends/Pods/Adjust/Adjust/ADJTimerOnce.m:92:5 -[ADJTimerOnce startIn:]
    NewWordsWithFriends/Pods/Adjust/Adjust/ADJAdditions/UIDevice+ADJAdditions.m:224:9 -[UIDevice(ADJAdditions) setiAdWithDetails:adcClientSharedInstance:iAdTimeoutTimer:]
    NewWordsWithFriends/Pods/Adjust/Adjust/ADJAdditions/UIDevice+ADJAdditions.m:194:36 -[UIDevice(ADJAdditions) adjCheckForiAd:iAdTimeoutTimer:]
    NewWordsWithFriends/Pods/Adjust/Adjust/ADJActivityHandler.m:1337:5 -[ADJActivityHandler checkForiAdI:]
    NewWordsWithFriends/Pods/Adjust/Adjust/ADJActivityHandler.m:799:9 -[ADJActivityHandler initI:preLaunchActionsArray:]
    NewWordsWithFriends/Pods/Adjust/Adjust/ADJActivityHandler.m:214:26 __52-[ADJActivityHandler initWithConfig:savedPreLaunch:]_block_invoke_2
    NewWordsWithFriends/Pods/Adjust/Adjust/ADJUtil.m:1240:9 __42+[ADJUtil launchInQueue:selfInject:block:]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_lane_serial_drain$VARIANT$armv81
    /usr/lib/system/libdispatch.dylib __dispatch_lane_invoke$VARIANT$armv81
    /usr/lib/system/libdispatch.dylib __dispatch_workloop_worker_thread
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread
```

We think it might be fixed in IOS 4.21.3

**Comment by uerceg** [comment]
Hi @smacgregor 

How did you end up using native iOS SDK version which has iAd timer inside of it? That was introduced in native iOS SDK v4.21.1 and our latest React Native SDK release uses iOS SDK v4.21.0 under the hood (either if added through [Cocoapods](https://github.com/adjust/react_native_sdk/blob/master/react-native-adjust.podspec#L21) or [without](https://github.com/adjust/react_native_sdk/blob/master/ios/Adjust/Adjust.h#L5)).

Cheers

**Comment by smacgregor** [comment]
Hmmm that is interesting great find. 

**package.json**
```
"react-native-adjust": "4.21",
```

**Podfile.lock**
```
PODS:
  - Adjust (4.21.2):
    - Adjust/Core (= 4.21.2)
  - Adjust/Core (4.21.2)
  - react-native-adjust (4.21.0):
    - Adjust (~> 4.21.0)
    - React
```

This must be an issue on our end. Feel free to close this out and I'll try to track down how our Podfile.lock picked up the wrong version here.

**Comment by smacgregor** [comment]
A follow up - I created a new sample react native project and then added Adjust:

```
yarn add react-native-adjust
cd ios
pod install
````
And it generated the same mismatched versions in Podfile.lock:

```
PODS:
  - Adjust (4.21.2):
    - Adjust/Core (= 4.21.2)
  - Adjust/Core (4.21.2)
  - react-native-adjust (4.21.0):
    - Adjust (~> 4.21.0)
    - React
```

**Comment by smacgregor** [comment]
FYI we blocked react-native-adjust@4.21.0 from pulling in Adjust 4.21.2 by manually adding a reference in our Podfile to

```
pod 'Adjust', '4.21.0'
```

But if that's the desired behavior on the Adjust side it probably makes sense to adjust the react native adjust podspec:

https://github.com/adjust/react_native_sdk/blob/master/react-native-adjust.podspec#L21

to confirm to 4.21.0 instead of ~> 4.21.0

**Comment by uerceg** [comment]
Hi @smacgregor 

Interesting, thanks for reporting this! I just tried your test from two comments above and got a bit different result than yours, but still not the expected one:

```
➜  ios pod install
Detected React Native module pod for react-native-adjust
Analyzing dependencies
Downloading dependencies
Installing Adjust (4.21.3)
Installing react-native-adjust (4.21.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 48 dependencies from the Podfile and 39 total pods installed.
```

So seems like in current setup, latest version of Pod is being pulled.

Definitely thanks for advice on version declaration, it will definitely be changed in upcoming patch release which will have pod version set to 4.21.3 where issue you saw should no longer exist.

Will keep you posted in here.

Cheers

**Comment by uerceg** [comment]
Hi @smacgregor 

Hopefully this should now be addressed in our [latest update](https://github.com/adjust/react_native_sdk/releases/tag/v4.22.0). For the record, here's the [current state](https://github.com/adjust/react_native_sdk/blob/master/react-native-adjust.podspec#L21) of podspec file.

Thanks for reporting and in case issue still persists, feel free to comment/reopen.

Cheers!
