### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.eventToken = eventToken'

### ISSUE THREAD

**Issue by mateusgomesti** [adjust/react_native_sdk#87]
![](https://user-images.githubusercontent.com/35661150/81433809-8a714b00-913b-11ea-8a3f-42caa5595b44.png)

I am running in debug mode on the iOS emulated, I have already reinstalled the app, installed pod install, reinstalled dependencies and got no results.

can anybody help me? I recently closed the contract.

Steps:

install dependence with: yarn add react-native-adjust --save
Add line in Podfile: pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'
Entrypoint.js file in my project add:
`import { Adjust, AdjustConfig } from 'react-native-adjust';`
and

```
const adjustConfig = new AdjustConfig('{multiplataformKey}', AdjustConfig.EnvironmentSandbox);
    Adjust.create(adjustConfig);
```

```
  componentWillUnmount() { // C
    Adjust.componentWillUnmount();
  }
```
LoginView.js add:
```
import { AdjustEvent } from 'react-native-adjust';
  renderFacebookLogin = () => (
    <Icon.Button
      onPress={() => {
        AdjustEvent(
          'kmii48'
        )
        this.fbLogin
      }}
 >
```
"react-native-adjust": "^4.21.0",
"react": "16.9.0",
"react-native": "0.61.2",

Details about my MainApplication.java add:

```
...
import com.adjust.nativemodule.AdjustPackage;

```

```
...
  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {

          @Override
          protected String getJSBundleFile(){
              return CodePush.getJSBundleFile();
          }

          @Override
          public boolean getUseDeveloperSupport() {
              return BuildConfig.DEBUG;
            }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          packages.add(new CodePush(codePushKey, getApplicationContext(), BuildConfig.DEBUG));
          packages.add(new RNFirebaseNotificationsPackage());
          packages.add(new RNFirebaseMessagingPackage());
          packages.add(new FBSDKPackage());
          packages.add(new RNFirebaseCrashlyticsPackage());
          packages.add(new RNFirebaseAnalyticsPackage());
          packages.add(new RNFirebaseLinksPackage());
          packages.add(new AdjustPackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };


```

I had created this issue by mistake in the adjust-android repository:
https://github.com/adjust/android_sdk/issues/442

**Comment by uerceg** [comment]
Hi @mateusgomesti 

When does this error happen, when you tap your button and invoke `onPress` method? What are you trying to achieve in that method, to track an event with `kmii48` token? Did you check how event tracking example looks like in our [example app](https://github.com/adjust/react_native_sdk/blob/master/example/App.js#L130)?

**Comment by ugi** [comment]
If still an issue, feel free to comment/reopen.
