### ISSUE TITLE
getGoogleAdId returns always null

### ISSUE THREAD

**Issue by lesocheck** [adjust/react_native_sdk#89]
Adjust.getGoogleAdId((googleAdId) => {
console.log("Google Ad Id = " + googleAdId);
});
returns always null

in log i see it

Parameters:
android_uuid 15699ad4-9df1-44a3-b3f7-ac73717c6d61
api_level 25
app_token 2fm9gkqubvpc
app_version 1.0
attribution_deeplink 1
callback_params {"scpk2":"scpv2"}
connectivity_type 1
country RU
cpu_type arm64-v8a
created_at 2020-05-28T10:07:11.461Z+0300
device_manufacturer Xiaomi
device_name Redmi 4X
device_type phone
display_height 1280
display_width 720
environment sandbox
event_buffering_enabled 0
event_count 1
event_token g3mfiw
gps_adid 119fe9c7-f7e1-420f-baae-eb1a31d6cad2

**Comment by uerceg** [comment]
Hi @lesocheck 

Thanks for reporting this, pretty interesting. 🤔 Seems to me that for some reason, React Native doesn't fancy approach of trying to read Google Advertising Id natively via service, but only from Google Play Services Library dependency.

Can you try adding following dependency to your app's `build.gradle` file:

```gradle
implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'
```

and retry?

Cheers

**Comment by lesocheck** [comment]
Thank's for answer.
But i get a build error

`ERROR: Gradle DSL method not found: ‘implementation()'Possible causes:The project ‘list’ may be using a version of Gradle that does not contain the method.<a href="open.wrapper file"> Open Gradle wrapper file</a> The build file may be missing a Gradle plugin.<a href="apply.gradle.plugin"> Apply Gradle plugin</a>`

i update gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.


buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.0")
        implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}`
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`

**Comment by uerceg** [comment]
Did it work after updating Gradle version? In case you want to use old Gradle version, if it complains about `implementation` keyword, then you should probably use `compile` instead.

**Comment by lesocheck** [comment]
`compile` dosn't work to. after updating Gradle version did not worl to

**Comment by uerceg** [comment]
Ah, now I noticed your Gradle file content. You added it to wrong file. You need to go to your `android/app` folder and edit Gradle file in there. For example in our example app in repo, this would be the place to add the dependency: https://github.com/adjust/react_native_sdk/blob/master/example/android/app/build.gradle

**Comment by lesocheck** [comment]
cool, man! it's work!!! i get gps_id!!! thank you a lot!!
