### ISSUE TITLE
Support RN >= 0.60 autolinking

### ISSUE THREAD

**Issue by gabriel-franzoni-pier** [adjust/react_native_sdk#94]
Running a project with either `react-native run-ios` or `react-native run-android` the following message appears:

```bash
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-adjust (to unlink run: "react-native unlink react-native-adjust")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

On the README section it's stated that `react-native link` is still needed.

**Comment by uerceg** [comment]
Hi @gabriel-franzoni-pier 

Did you add Adjust SDK to your app while it was using RN version prior to 0.60 and you upgraded RN version to 0.60 or later in the meantime?

Does it work for you if you unlink, like suggested in error message?

**Comment by gabriel-franzoni-pier** [comment]
I am using a brand-new project with RN 0.62.

What I meant is that without running `react-native link` the lib won't work properly, so I am requesting support for autolinking :)

Answering directly your question:
>*Does it work for you if you unlink, like suggested in error message?*

Nope, it bugs intermittently on iOS

**Comment by Hemistone** [comment]
Is there any update about autolinking support? There is no mention about autolinking in docs, still.

**Comment by ugi** [comment]
Hey guys,

We'll try to add support for this in next patch release. Will keep you posted.

**Comment by gziolle** [comment]
Hi!

Is there any news about this issue?

**Comment by ugi** [comment]
Hey!

Yes, we're working on it and should hopefully release an update soon which will try to address this issue.

**Comment by beetlebum** [comment]
Any updates on this issue? thanks.

**Comment by uerceg** [comment]
Hey @beetlebum Yes, we're working on it and aim to have release out next week.

**Comment by beetlebum** [comment]
> Hey @beetlebum Yes, we're working on it and aim to have release out next week.

@uerceg thanks for the reply, is the workaround currently to do the linking manually and skip the `react-native link` step or is it better to wait for the next release?

**Comment by uerceg** [comment]
@beetlebum If that doesn't harm your app, you can give it a shot, but probably better to wait for next release. I actually think we might be able to push it out tomorrow.

**Comment by beetlebum** [comment]
@uerceg great, we'll wait, thanks

**Comment by uerceg** [comment]
Hey guys,

We just released v4.23.1 update where we tried to add support for auto linking. If you can please give it a shot and let us know if it works as expected.

Cheers

**Comment by uerceg** [comment]
Hey guys, did anyone give this version a shot and checked if auto linking warning is gone and that it's being performed?

**Comment by beetlebum** [comment]
@uerceg we've done an integration and haven't had any issues, although we never installed the previous version so can't really compare.

**Comment by uerceg** [comment]
Thanks @beetlebum for the feedback. I'll close the issue, but in case needed, feel free to comment/reopen. Cheers!
