### ISSUE TITLE
[ANDROID] Deferred deeplink doesn't redirect to exact page - don't work at all.

### ISSUE THREAD

**Issue by dkfl1995** [adjust/react_native_sdk#96]
The example adjust specific links I use to test deferred deeplinking: 
[](https://app.adjust.com/<tracker id>?deep_link=https%3A%2F%2Fqa-brandsforless.bfl.dev%2Fen-ae%2Frobot-triceratops-tee%2F999%2Fp%2F)
[](https://app.adjust.com/<tracker id>?deep_link=https%3A%2F%2Fqa-brandsforless.bfl.dev%2Fen-ae%2Fwomen%2Fclothing%2Fbodysuit%2F).

Step to repro:
1. If app is not installed on device, redirecting to specified Custom URL (3-d party .apk sharing platform). 
2. After FIRST STEP, app is downloaded and installed successfully, so I'm starting it, and then application should open `deep_link` url as an Adjust callback. But it do not.

**Comment by ugi** [comment]
Hi @dkfl1995 

So the thing which doesn't work for you is the scenario in which you already have an app installed on your device and then you click on this tracker URL from above?

What do you expect to happen in that moment and what is happening instead?

Cheers

**Comment by dkfl1995** [comment]
Hey @ugi 

Literally you did not catch the thing. You can see the steps I do in the first message, and the last is not as expected. Please refer.

In short, deferred deeplinking (the case when app was not installed before tap the adjust specific link) let me to url to download app as well as installation is going as expected, but after opening it wont navigate me to `deep_link` url.

**Comment by ugi** [comment]
Okay. Did you set up your app to handle this link you are assigning as value to `deep_link` parameter?

**Comment by dkfl1995** [comment]
@ugi Yes, I did everything on that own

**Comment by uerceg** [comment]
👋 Hi @dkfl1995,

Sorry for coming back to this one after big delay, but wanted to ask if you managed to figure out what the issue was? If you're still having troubles with this, let us know and we can try to check with our support team.

Cheers
