### ISSUE TITLE
Stuck in "WAITING FOR DATA FROM YOUR APP"

### ISSUE THREAD

**Issue by brerdem** [adjust/react_native_sdk#99]
Installed the SDK as in the instruction, still can't see an activity on dashboard. Testing on iOS

Adjust SDK version: react-native4.22.0@ios4.22.1
RN version : 0.61.5

**Comment by ugi** [comment]
Hi @brerdem 

Did you manage to figure it out? Have you checked if your traffic is sent to sandbox traffic?

**Comment by ugi** [comment]
If still an issue, feel free to comment/reopen.

Cheers
